In [1]:
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np

In [2]:
output_dir = 'data'
file_path = './data/sample.png'

In [3]:
img = load_img(file_path)

In [4]:
img_resize = img.resize((229, 229))

In [5]:
img_np = np.array(img_resize) / 255.0

In [6]:
img_np.shape

(229, 229, 3)

In [8]:
img_np[:2]

array([[[0.75686275, 0.42745098, 0.28627451],
        [0.77254902, 0.44313725, 0.30196078],
        [0.76078431, 0.43137255, 0.29411765],
        ...,
        [0.43137255, 0.21176471, 0.18431373],
        [0.30588235, 0.1372549 , 0.1254902 ],
        [0.24313725, 0.12156863, 0.11764706]],

       [[0.76862745, 0.43921569, 0.29803922],
        [0.75686275, 0.42745098, 0.28627451],
        [0.74509804, 0.41568627, 0.27843137],
        ...,
        [0.30588235, 0.14509804, 0.12156863],
        [0.22745098, 0.10588235, 0.09411765],
        [0.19607843, 0.11764706, 0.10980392]]])

In [10]:
img_array = np.expand_dims(img_np, axis=0)

In [11]:
img_array.shape

(1, 229, 229, 3)

In [12]:
generator = ImageDataGenerator(
    horizontal_flip=0.3
)

In [15]:
generator.fit(img_array)

In [16]:
img_array.shape

(1, 229, 229, 3)

In [17]:
img_array[0][:2]

array([[[0.75686275, 0.42745098, 0.28627451],
        [0.77254902, 0.44313725, 0.30196078],
        [0.76078431, 0.43137255, 0.29411765],
        ...,
        [0.43137255, 0.21176471, 0.18431373],
        [0.30588235, 0.1372549 , 0.1254902 ],
        [0.24313725, 0.12156863, 0.11764706]],

       [[0.76862745, 0.43921569, 0.29803922],
        [0.75686275, 0.42745098, 0.28627451],
        [0.74509804, 0.41568627, 0.27843137],
        ...,
        [0.30588235, 0.14509804, 0.12156863],
        [0.22745098, 0.10588235, 0.09411765],
        [0.19607843, 0.11764706, 0.10980392]]])

In [18]:
iter = generator.flow(img_array, batch_size=1)

In [19]:
iter.next()

array([[[[0.75686276, 0.42745098, 0.28627452],
         [0.77254903, 0.44313726, 0.3019608 ],
         [0.7607843 , 0.43137255, 0.29411766],
         ...,
         [0.43137255, 0.21176471, 0.18431373],
         [0.30588236, 0.13725491, 0.1254902 ],
         [0.24313726, 0.12156863, 0.11764706]],

        [[0.76862746, 0.4392157 , 0.29803923],
         [0.75686276, 0.42745098, 0.28627452],
         [0.74509805, 0.41568628, 0.2784314 ],
         ...,
         [0.30588236, 0.14509805, 0.12156863],
         [0.22745098, 0.10588235, 0.09411765],
         [0.19607843, 0.11764706, 0.10980392]],

        [[0.76862746, 0.4392157 , 0.29803923],
         [0.7647059 , 0.43529412, 0.29411766],
         [0.75686276, 0.42745098, 0.29411766],
         ...,
         [0.21176471, 0.11372549, 0.10196079],
         [0.18431373, 0.10980392, 0.10588235],
         [0.1764706 , 0.12156863, 0.11764706]],

        ...,

        [[0.39215687, 0.21960784, 0.1764706 ],
         [0.4392157 , 0.23529412, 0.18039216]